name: CI - Build Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t flask-devops .

      - name: Tag Docker image
        run: docker tag flask-devops pradeev812/flask-devops:latest

      - name: Push Docker image to DockerHub
        run: docker push pradeev812/flask-devops:latest

      - name: Decode PEM key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > key.pem
          chmod 400 key.pem

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull pradeev812/flask_devops:latest
            docker stop flask-devops || true
            docker rm flask-decvops || true
            docker run -d -p 5000:5000 --name flask_devops pradeev812/flask-devops:latest
          EOF

